// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RequestType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Game.Core.Network {

  /// <summary>Holder for reflection information generated from RequestType.proto</summary>
  public static partial class RequestTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for RequestType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RequestTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFSZXF1ZXN0VHlwZS5wcm90bxIRZ2FtZS5jb3JlLm5ldHdvcmsqOQoLUmVx",
            "dWVzdFR5cGUSFAoQU0VSVkVSX1RPX0NMSUVOVBAAEhQKEENMSUVOVF9UT19T",
            "RVJWRVIQAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Game.Core.Network.RequestType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum RequestType {
    [pbr::OriginalName("SERVER_TO_CLIENT")] ServerToClient = 0,
    [pbr::OriginalName("CLIENT_TO_SERVER")] ClientToServer = 1,
  }

  #endregion

}

#endregion Designer generated code
