// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ResponseMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Game.Core.Network {

  /// <summary>Holder for reflection information generated from ResponseMessage.proto</summary>
  public static partial class ResponseMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for ResponseMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResponseMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVSZXNwb25zZU1lc3NhZ2UucHJvdG8SEWdhbWUuY29yZS5uZXR3b3JrGhFS",
            "ZXF1ZXN0VHlwZS5wcm90bxoZZ29vZ2xlL3Byb3RvYnVmL2FueS5wcm90byKY",
            "AQoPUmVzcG9uc2VNZXNzYWdlEhIKCnJlc3BvbnNlSWQYASABKAkSLAoEdHlw",
            "ZRgCIAEoDjIeLmdhbWUuY29yZS5uZXR3b3JrLlJlcXVlc3RUeXBlEgwKBHBh",
            "dGgYAyABKAkSIgoEYm9keRgEIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnkS",
            "EQoJc3RhdGVDb2RlGAUgASgFYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Game.Core.Network.RequestTypeReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Core.Network.ResponseMessage), global::Game.Core.Network.ResponseMessage.Parser, new[]{ "ResponseId", "Type", "Path", "Body", "StateCode" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ResponseMessage : pb::IMessage<ResponseMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResponseMessage> _parser = new pb::MessageParser<ResponseMessage>(() => new ResponseMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResponseMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Core.Network.ResponseMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponseMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponseMessage(ResponseMessage other) : this() {
      responseId_ = other.responseId_;
      type_ = other.type_;
      path_ = other.path_;
      body_ = other.body_ != null ? other.body_.Clone() : null;
      stateCode_ = other.stateCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponseMessage Clone() {
      return new ResponseMessage(this);
    }

    /// <summary>Field number for the "responseId" field.</summary>
    public const int ResponseIdFieldNumber = 1;
    private string responseId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ResponseId {
      get { return responseId_; }
      set {
        responseId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::Game.Core.Network.RequestType type_ = global::Game.Core.Network.RequestType.ServerToClient;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Game.Core.Network.RequestType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "path" field.</summary>
    public const int PathFieldNumber = 3;
    private string path_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Path {
      get { return path_; }
      set {
        path_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "body" field.</summary>
    public const int BodyFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Any body_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any Body {
      get { return body_; }
      set {
        body_ = value;
      }
    }

    /// <summary>Field number for the "stateCode" field.</summary>
    public const int StateCodeFieldNumber = 5;
    private int stateCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int StateCode {
      get { return stateCode_; }
      set {
        stateCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResponseMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResponseMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResponseId != other.ResponseId) return false;
      if (Type != other.Type) return false;
      if (Path != other.Path) return false;
      if (!object.Equals(Body, other.Body)) return false;
      if (StateCode != other.StateCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ResponseId.Length != 0) hash ^= ResponseId.GetHashCode();
      if (Type != global::Game.Core.Network.RequestType.ServerToClient) hash ^= Type.GetHashCode();
      if (Path.Length != 0) hash ^= Path.GetHashCode();
      if (body_ != null) hash ^= Body.GetHashCode();
      if (StateCode != 0) hash ^= StateCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ResponseId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ResponseId);
      }
      if (Type != global::Game.Core.Network.RequestType.ServerToClient) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (Path.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Path);
      }
      if (body_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Body);
      }
      if (StateCode != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(StateCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ResponseId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ResponseId);
      }
      if (Type != global::Game.Core.Network.RequestType.ServerToClient) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (Path.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Path);
      }
      if (body_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Body);
      }
      if (StateCode != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(StateCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ResponseId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResponseId);
      }
      if (Type != global::Game.Core.Network.RequestType.ServerToClient) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Path.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Path);
      }
      if (body_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Body);
      }
      if (StateCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StateCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResponseMessage other) {
      if (other == null) {
        return;
      }
      if (other.ResponseId.Length != 0) {
        ResponseId = other.ResponseId;
      }
      if (other.Type != global::Game.Core.Network.RequestType.ServerToClient) {
        Type = other.Type;
      }
      if (other.Path.Length != 0) {
        Path = other.Path;
      }
      if (other.body_ != null) {
        if (body_ == null) {
          Body = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Body.MergeFrom(other.Body);
      }
      if (other.StateCode != 0) {
        StateCode = other.StateCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ResponseId = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::Game.Core.Network.RequestType) input.ReadEnum();
            break;
          }
          case 26: {
            Path = input.ReadString();
            break;
          }
          case 34: {
            if (body_ == null) {
              Body = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Body);
            break;
          }
          case 40: {
            StateCode = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ResponseId = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::Game.Core.Network.RequestType) input.ReadEnum();
            break;
          }
          case 26: {
            Path = input.ReadString();
            break;
          }
          case 34: {
            if (body_ == null) {
              Body = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Body);
            break;
          }
          case 40: {
            StateCode = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
